apiVersion: v1
kind: Service
metadata:
  name: cloud-native-website
  labels:
    app: cloud-native-website
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: cloud-native-website
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-native-website-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-native-website
        version: v1
    spec:
      containers:
      - name: cloud-native-website
        image: 955065381857.dkr.ecr.cn-north-1.amazonaws.com.cn/cloud-native-website:BUILD_VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: new-secret
